### ISSUE TITLE
Dockerize Front (React)

### ISSUE THREAD

**Issue by martin-one** [IntersysConsulting/ingangsters-web#11]

**Comment by jogadev** [comment]
There is a problem:
I want to create a real-time development environment with Docker, so we can edit our code and it would be automatically refreshed within the container. To do so, we use volumes, but the problem is that out Azure credentials won't give Docker the proper permissions to create volumes.

**Comment by martin-one** [comment]
https://tomssl.com/2018/01/11/sharing-your-c-drive-with-docker-for-windows-when-using-azure-active-directory-azuread-aad/
This one worked for me. (grant access to C in docker)

**Comment by sofia-robles-Intersys** [comment]
`#Base Image
FROM node:10.16.2
#Create directory for container
RUN mkdir -p /app
WORKDIR /app
#Copy files to container
COPY "package.json" "/app/"
COPY "package-lock.json" "/app/"
#install dependencies
RUN npm install
#create-react-app version: 3.1.1
RUN npm install -g create-react-app
#Adding Application files to the container
ADD "src" "/app/src"
ADD "public" "/app/public"
#Setting the enviromental variable to true to enable hot-reload
ENV CHOKIDAR_USEPOLLING true
#Set port
EXPOSE 3000
CMD ["npm","start"]
`

**Comment by sofia-robles-Intersys** [comment]
[Dockerfile.txt](https://github.com/IntersysConsulting/ingangsters-web/files/3521412/Dockerfile.txt)


Me comento Edgardo que la linea que dice: RUN npm install -g create-react-app
no es necesaria si la aplicación ya está creada.

**Comment by sofia-robles-Intersys** [comment]
Para construir la imagen ejecutar 
docker build -t react_test .

Para correr el contenedor
docker run -p 3000:3000  -v ${PWD}:/app -v /app/node_modules react_test

**Comment by jogadev** [comment]
Dockerfile
```
FROM node

WORKDIR /app

COPY . /app

RUN npm i

ENV CHOKIDAR_USEPOLLING true

CMD ["npm","start"]
```


.dockerignore
```
*
!package.json
!package-lock.json
!/src
!/public
```
