### ISSUE TITLE
Finish existing mockups

### ISSUE THREAD

**Issue by jogadev** [IntersysConsulting/ingangsters-web#18]
Apply new color palette on the existing mockups and standardize  product overview, product and users administration.

**Comment by zkdna** [comment]
All the unexpected mockups, and the previous revisions to the old ones were finished. All the windows are located in the following link, and every team member has access.

https://www.figma.com/file/H3r2owBm4H2Cq4x1TvtDJw/Ecommerce?node-id=9%3A2
