### ISSUE TITLE
Create project structure

### ISSUE THREAD

**Issue by jogadev** [IntersysConsulting/ingangsters-web#19]
Define folder distribution for the project components.

**Comment by JAndresHJ** [comment]
Creo esta estructura puede servirnos. Me basé en los siguientes blogs para hacerla por si quieren indagar en detalles. Espero su retroalimentación 

_https://medium.com/@Charles_Stover/optimal-file-structure-for-react-applications-f3e35ad0a145_

_https://jslancer.com/blog/2018/09/17/organize-react-redux-project/_

ESTRUCTURA:

e-commerce
├── build
├── node_modules
├── public
│   ├── favicon.ico
│   ├── index.html
│   └── manifest.json
├── src
│   ├── assets
│   │   └──images
│   │      └── logo.svg
│   ├── components
│   │   └── component-name
│   │   │  ├── component-name.css
│   │   │  ├── component-name.test.js
│   │   │  └── component-name.js
│   ├── utils
│   ├── index.css
│   ├── index.js
│   └── service-worker.js
├── actions
├── reducers
├── .gitignore
├── package.json
└── README.md
