### ISSUE TITLE
Create a general color file related to our theming 

### ISSUE THREAD

**Issue by JAndresHJ** [IntersysConsulting/ingangsters-web#27]

**Comment by sofia-robles-Intersys** [comment]
The colors dictionary is merged in the development branch.
* {
  --dark-grey: #55565a;
  --light-grey: #c4c4c4;
  --green: #6cc04a;
  --light-blue: #0071ce;
  --orange: #f98f3e;
  --red: #ce2500;
}


To have access to it add import "../../css/colors.css"; in your component file
