### ISSUE TITLE
Design - Sign Up - Users

### ISSUE THREAD

**Issue by martin-one** [IntersysConsulting/ingangsters-web#4]

**Comment by martin-one** [comment]
[index_base.zip](https://github.com/IntersysConsulting/ingangsters-web/files/3483924/index_base.zip)
Algo asi quedaria la base, solo con la cabecera

**Comment by zkdna** [comment]
Done...

https://www.figma.com/file/H3r2owBm4H2Cq4x1TvtDJw/Sign-Up?node-id=0%3A1
