### ISSUE TITLE
Design Confirmation alerts and actions

### ISSUE THREAD

**Issue by zkdna** [IntersysConsulting/ingangsters-web#91]

**Comment by jogadev** [comment]
![confirmation modal](https://user-images.githubusercontent.com/48494652/66002474-647b1e00-e469-11e9-8efa-f5b3027b1fc1.PNG)

This is my idea. What do you think? @zkdna @JAndresHJ @martin-one 
Todo el texto que se ve en el modal sería configurable via props

**Comment by martin-one** [comment]
A mi me parece bien, me gusta.

**Comment by JAndresHJ** [comment]
Igual me late! sólo cuidado con el typo de "de"
